"""Python API for BiRefNet_dynamic phone product normalization."""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Optional, Sequence, Tuple, Union

from PIL import Image

try:
    # In a source checkout ``scripts`` is a sibling package.  It is included in
    # the wheel by pyproject.toml as well, so this import also works after
    # installation.
    from scripts.segmentation import (
        DEFAULT_MAX_GEOMETRY_PIXELS,
        DEFAULT_BIREFNET_CPU_FALLBACK_MAX_SIDE,
        DEFAULT_BIREFNET_MAX_SIDE,
        SUPPORTED_DEVICES,
        GeometryConfig,
        NormalizationInfo,
        create_segmentation_backend,
        normalize_image,
        _clear_exception_traceback,
        _release_torch_memory,
        parse_birefnet_max_side,
        parse_birefnet_resolution,
        parse_max_geometry_pixels,
        validate_geometry_size,
    )
except ModuleNotFoundError as exc:  # pragma: no cover - protects unusual installs
    raise RuntimeError(
        "the bundled normalization core is missing; install the project with "
        "pip install -e . or run from phone-product-normalizer/"
    ) from exc


DEFAULT_BACKEND = "birefnet"
DEFAULT_MODEL = "ZhengPeng7/BiRefNet_dynamic"
DEFAULT_OUTPUT_DIR = Path("outputs") / "结果"
IMAGE_EXTENSIONS = frozenset(
    {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".bmp"}
)

# Directory names generated by this project, virtual environments, and common
# source-control folders are pruned while collecting a directory input.  A
# caller can still pass a generated image as an explicit file path.
EXCLUDED_DIRECTORY_NAMES = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "__pycache__",
        "node_modules",
        "build",
        "dist",
        "outputs",
        "结果",
    }
)

PathLike = Union[str, os.PathLike[str], Path]
ProgressCallback = Callable[[int, int, Path], None]


@dataclass(frozen=True)
class NormalizerConfig:
    """Geometry and device settings for BiRefNet_dynamic."""

    backend: str = DEFAULT_BACKEND
    model: Optional[str] = None
    device: str = "auto"
    birefnet_resolution: Any = "auto"

    geometry_threshold: int = 32
    crop_threshold: int = 8
    max_deskew_degrees: float = 45.0
    confidence_floor: float = 0.55
    remove_support: bool = True
    deskew: bool = True
    tight_crop: bool = True
    require_support_border: bool = False
    # Dynamic BiRefNet safety controls.  They are appended after the original
    # fields to keep positional construction of older configs compatible.
    # ``"auto"`` selects the conservative 1024-pixel cap; ``"none"`` (or
    # ``None`` programmatically) explicitly opts out of the cap.
    birefnet_max_side: Any = "auto"
    birefnet_cpu_fallback_max_side: Any = DEFAULT_BIREFNET_CPU_FALLBACK_MAX_SIDE
    birefnet_memory_cleanup: bool = True
    birefnet_fallback_to_cpu: bool = True
    # Full-resolution geometry scratch buffers are guarded independently from
    # the model-input cap.  Keep this new option at the end so positional
    # construction of older configs remains compatible; ``None``/``"none"``
    # opts out for a controlled caller that can guarantee sufficient memory.
    max_geometry_pixels: Any = DEFAULT_MAX_GEOMETRY_PIXELS

    def __post_init__(self) -> None:
        backend = str(self.backend).strip().lower()
        if backend != DEFAULT_BACKEND:
            raise ValueError("Only BiRefNet_dynamic is supported")
        if self.model not in (None, DEFAULT_MODEL):
            raise ValueError("Only BiRefNet_dynamic is supported")
        object.__setattr__(self, "backend", backend)
        if str(self.device).strip().lower() not in SUPPORTED_DEVICES:
            raise ValueError(
                f"unsupported device {self.device!r}; choose one of {', '.join(SUPPORTED_DEVICES)}"
            )
        for name in ("geometry_threshold", "crop_threshold"):
            value = int(getattr(self, name))
            if not 1 <= value <= 254:
                raise ValueError(f"{name} must be between 1 and 254")
            object.__setattr__(self, name, value)
        max_deskew = float(self.max_deskew_degrees)
        if max_deskew < 0.0:
            raise ValueError("max_deskew_degrees cannot be negative")
        object.__setattr__(self, "max_deskew_degrees", max_deskew)
        confidence = float(self.confidence_floor)
        if not 0.0 <= confidence <= 1.0:
            raise ValueError("confidence_floor must be between 0 and 1")
        object.__setattr__(self, "confidence_floor", confidence)
        object.__setattr__(
            self,
            "max_geometry_pixels",
            parse_max_geometry_pixels(self.max_geometry_pixels),
        )
        if backend == "birefnet":
            # Validate early so a typo is reported before a model is loaded.
            parse_birefnet_resolution(self.birefnet_resolution)
            parse_birefnet_max_side(self.birefnet_max_side)
            parse_birefnet_max_side(self.birefnet_cpu_fallback_max_side)

    @property
    def effective_model(self) -> Optional[str]:
        """Model id passed to the selected backend factory."""

        return DEFAULT_MODEL

    @property
    def parsed_birefnet_resolution(self) -> Optional[Tuple[int, int]]:
        """Return the parsed BiRefNet resolution, with ``None`` meaning auto."""

        return parse_birefnet_resolution(self.birefnet_resolution)

    @property
    def parsed_birefnet_max_side(self) -> Optional[int]:
        """Return the dynamic long-side cap, or ``None`` when disabled."""

        return parse_birefnet_max_side(self.birefnet_max_side)

    @property
    def parsed_birefnet_cpu_fallback_max_side(self) -> Optional[int]:
        """Return the cap used by the automatic MPS→CPU retry."""

        return parse_birefnet_max_side(self.birefnet_cpu_fallback_max_side)

    def geometry(self) -> GeometryConfig:
        """Build the lower-level geometry configuration used by the core."""

        return GeometryConfig(
            geometry_threshold=self.geometry_threshold,
            crop_threshold=self.crop_threshold,
            max_deskew_degrees=self.max_deskew_degrees,
            require_support_border=self.require_support_border,
            max_geometry_pixels=self.max_geometry_pixels,
        )


# Public alias for the core's serialisable diagnostics dataclass.  Keeping a
# stable name here lets callers avoid importing an implementation module.
ProcessingInfo = NormalizationInfo


@dataclass(frozen=True)
class FileResult:
    """Result of one file operation."""

    source: Path
    output: Optional[Path] = None
    metadata: Optional[Path] = None
    info: Optional[ProcessingInfo] = None
    error: Optional[str] = None

    @property
    def succeeded(self) -> bool:
        return self.error is None and self.output is not None


BatchResult = FileResult


def _as_path(value: PathLike) -> Path:
    return Path(value).expanduser()


def _is_image(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS


def _safe_resolve(path: Path) -> Path:
    """Resolve a path without making callers handle transient filesystem errors."""

    try:
        return path.resolve()
    except OSError:
        # ``resolve`` can fail for a dangling symlink or a directory that is
        # removed while a batch is being collected.  ``absolute`` still gives
        # us a stable path for the containment checks below.
        return path.absolute()


def _path_key(path: Path) -> str:
    """Return a comparison key that is safe on case-insensitive filesystems."""

    return str(_safe_resolve(path)).casefold()


def _is_within(path: Path, directory: Path, *, include_self: bool = True) -> bool:
    """Whether *path* is inside *directory* without string-prefix mistakes."""

    path = _safe_resolve(path)
    directory = _safe_resolve(directory)
    if not include_self and path == directory:
        return False
    try:
        path.relative_to(directory)
    except ValueError:
        return False
    return True


def _iter_directory(
    directory: Path,
    recursive: bool,
    *,
    excluded_directories: Sequence[Path] = (),
) -> Iterable[Path]:
    """Yield supported image paths in deterministic order.

    ``excluded_directories`` is intentionally applied only while expanding a
    directory.  An explicitly supplied image file remains processable, even
    when it lives below an excluded result directory; the allocator will then
    choose a safe ``-processed`` output name.
    """

    excluded = tuple(_safe_resolve(item) for item in excluded_directories)
    directory = _safe_resolve(directory)
    if any(_is_within(directory, item) for item in excluded):
        return

    if recursive:
        for root, dirnames, filenames in os.walk(directory, followlinks=False):
            root_path = _safe_resolve(Path(root))
            if any(_is_within(root_path, item) for item in excluded):
                # This can happen when an excluded path is reached through a
                # symlink or when the filesystem changes during os.walk.
                dirnames[:] = []
                continue
            kept_dirs: list[str] = []
            for name in sorted(dirnames, key=str.casefold):
                if name in EXCLUDED_DIRECTORY_NAMES or name.startswith("."):
                    continue
                child = _safe_resolve(Path(root) / name)
                if any(_is_within(child, item) for item in excluded):
                    continue
                kept_dirs.append(name)
            dirnames[:] = kept_dirs
            for name in sorted(filenames, key=str.casefold):
                if name.startswith("."):
                    continue
                path = Path(root) / name
                if _is_image(path):
                    yield path
    else:
        for path in sorted(directory.iterdir(), key=lambda item: item.name.casefold()):
            if not path.name.startswith(".") and _is_image(path):
                yield path


def collect_image_paths(
    inputs: Sequence[PathLike],
    *,
    recursive: bool = True,
    excluded_directories: Sequence[PathLike] = (),
) -> list[Path]:
    """Expand files/folders into a stable, de-duplicated image list.

    Unsupported and missing paths are ignored so drag-and-drop callers may
    include a mixture of files.  :class:`Normalizer` raises a concise error if
    no supported image remains.
    """

    excluded = tuple(_safe_resolve(_as_path(item)) for item in excluded_directories)
    found: list[Path] = []
    seen: set[str] = set()
    for raw in inputs:
        path = _as_path(raw)
        resolved = _safe_resolve(path)
        if resolved.is_dir():
            candidates: Iterable[Path] = _iter_directory(
                resolved,
                recursive,
                excluded_directories=excluded,
            )
        elif _is_image(resolved):
            candidates = (resolved,)
        else:
            candidates = ()
        for candidate in candidates:
            try:
                normalized = candidate.resolve()
            except OSError:
                continue
            key = _path_key(normalized)
            if key not in seen:
                seen.add(key)
                found.append(normalized)
    return sorted(found, key=lambda item: str(item).casefold())


def _allocate_output_paths(
    sources: Sequence[Path], output_dir: Path
) -> list[tuple[Path, Path]]:
    """Create collision-free PNG/JSON paths while preserving source stems.

    In addition to duplicate stems, account for files already present in the
    destination and for PNG inputs whose natural output path is the input
    itself.  The latter receives ``-processed`` (then ``-processed-2`` and so
    on), while ordinary duplicate stems retain the familiar ``-2``, ``-3``
    sequence.  Both the PNG and its JSON sidecar are reserved together so a
    rerun cannot silently overwrite either artifact.
    """

    output_dir = _safe_resolve(output_dir)
    source_keys = {_path_key(source) for source in sources}
    # Existing files are treated as occupied even when they are stale output;
    # preserving them makes rerunning a batch recoverable and deterministic.
    occupied: set[str] = set(source_keys)
    try:
        existing = tuple(output_dir.iterdir())
    except OSError:
        existing = ()
    occupied.update(_path_key(item) for item in existing)

    stem_counts: dict[str, int] = {}
    result: list[tuple[Path, Path]] = []

    def candidate_paths(base: str) -> tuple[Path, Path]:
        return output_dir / f"{base}.png", output_dir / f"{base}.json"

    def available(output: Path, metadata: Path) -> bool:
        return _path_key(output) not in occupied and _path_key(metadata) not in occupied

    for source in sources:
        stem = source.stem or "image"
        stem_key = stem.casefold()
        occurrence = stem_counts.get(stem_key, 0) + 1
        stem_counts[stem_key] = occurrence

        if occurrence == 1:
            base = stem
            output, metadata = candidate_paths(base)
            if not available(output, metadata):
                # A PNG source (or an existing result from an earlier run)
                # must never be overwritten.
                base = f"{stem}-processed"
                output, metadata = candidate_paths(base)
                serial = 2
                while not available(output, metadata):
                    base = f"{stem}-processed-{serial}"
                    output, metadata = candidate_paths(base)
                    serial += 1
        else:
            serial = occurrence
            base = f"{stem}-{serial}"
            output, metadata = candidate_paths(base)
            while not available(output, metadata):
                serial += 1
                base = f"{stem}-{serial}"
                output, metadata = candidate_paths(base)

        occupied.add(_path_key(output))
        occupied.add(_path_key(metadata))
        result.append((output, metadata))
    return result


def _json_safe(value: Any) -> Any:
    """Convert paths/tuples/numpy-ish scalars for metadata serialization."""

    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    # Dataclasses from the core are handled by asdict before this helper.  The
    # scalar fallback keeps custom metadata extensions JSON-friendly without
    # importing numpy just for serialization.
    if hasattr(value, "item") and callable(value.item):
        try:
            return value.item()
        except Exception:
            pass
    return value


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(_json_safe(dict(payload)), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _metadata_payload(
    source: Path,
    output: Optional[Path],
    info: Optional[ProcessingInfo],
    *,
    config: NormalizerConfig,
    error: Optional[str] = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "success": error is None and info is not None,
        "source": str(source),
        "output": (str(output) if output is not None else None),
        "requested_backend": config.backend,
        "requested_model": config.effective_model,
        "requested_device": config.device,
    }
    if info is not None:
        payload.update(asdict(info))
    if error is not None:
        payload["error"] = error
    return payload


class Normalizer:
    """Reusable segment-and-normalize pipeline.

    A single instance caches its backend, so a batch loads a large model only
    once.  Pass ``backend_instance`` to inject a fake or custom backend in
    tests and applications; it must expose ``segment(image)`` or be callable,
    just like the legacy core API.
    """

    def __init__(
        self,
        config: Optional[NormalizerConfig] = None,
        *,
        backend_instance: Optional[Any] = None,
    ) -> None:
        self.config = config or NormalizerConfig()
        self._backend = backend_instance
        # An injected backend belongs to the caller.  ``close`` will detach
        # it from this wrapper but will not invoke an arbitrary custom
        # ``close`` method behind the caller's back.
        self._owns_backend = backend_instance is None

    def close(self) -> None:
        """Release the cached backend and accelerator memory.

        A :class:`Normalizer` intentionally keeps one model alive so a batch
        does not reload weights for every image.  Call ``close`` when the
        instance will no longer be used (or use it as a context manager) so a
        long-running host process can return the model and allocator cache to
        the system.  Cleanup is best-effort and never masks a prior error.
        """

        backend = self._backend
        self._backend = None
        device = str(getattr(backend, "device", self.config.device))
        close = None
        if backend is not None and self._owns_backend:
            close = getattr(backend, "close", None)
            if callable(close):
                try:
                    close()
                except Exception:
                    pass
        # Drop this local reference before trimming the allocator; otherwise a
        # backend-owned model can remain reachable through this frame.
        del close
        del backend
        _release_torch_memory(device)

    # ``release`` is a convenient spelling for integrations that already use
    # that lifecycle term; both names have identical semantics.
    release = close

    def __enter__(self) -> "Normalizer":
        return self

    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool:
        self.close()
        return False

    @property
    def backend(self) -> Any:
        """Lazily construct and cache the selected segmentation backend."""

        if self._backend is None:
            self._backend = create_segmentation_backend(
                self.config.backend,
                model_name=self.config.effective_model,
                device=self.config.device,

                birefnet_resolution=self.config.parsed_birefnet_resolution,
                birefnet_max_side=self.config.parsed_birefnet_max_side,
                birefnet_cpu_fallback_max_side=self.config.parsed_birefnet_cpu_fallback_max_side,
                birefnet_memory_cleanup=self.config.birefnet_memory_cleanup,
                birefnet_fallback_to_cpu=self.config.birefnet_fallback_to_cpu,
            )
        return self._backend

    def normalize(self, image: Image.Image) -> tuple[Image.Image, ProcessingInfo]:
        """Normalize one in-memory image and return PNG-ready RGBA + metadata."""

        # Validate before evaluating ``self.backend`` below.  The backend is
        # lazy and can load a multi-gigabyte model; rejecting an accidental
        # panorama/scan first keeps that allocation out of an input-error
        # path.  EXIF orientation can swap width/height but never changes the
        # pixel count, so the decoded image size is sufficient here.
        if self.config.remove_support or self.config.deskew or self.config.tight_crop:
            validate_geometry_size(
                (int(image.size[0]), int(image.size[1])),
                self.config.max_geometry_pixels,
            )
        return normalize_image(
            image,
            backend=self.backend,
            geometry_config=self.config.geometry(),
            birefnet_resolution=self.config.parsed_birefnet_resolution,
            birefnet_max_side=self.config.parsed_birefnet_max_side,
            birefnet_cpu_fallback_max_side=self.config.parsed_birefnet_cpu_fallback_max_side,
            birefnet_memory_cleanup=self.config.birefnet_memory_cleanup,
            birefnet_fallback_to_cpu=self.config.birefnet_fallback_to_cpu,
            confidence_floor=self.config.confidence_floor,
            remove_support=self.config.remove_support,
            deskew=self.config.deskew,
            tight_crop=self.config.tight_crop,
        )

    def process_file(
        self,
        source_path: PathLike,
        output_path: PathLike,
        *,
        metadata_path: Optional[PathLike] = None,
    ) -> FileResult:
        """Process one source file without ever overwriting that source."""

        source = _as_path(source_path).resolve()
        output = _as_path(output_path).resolve()
        metadata = _as_path(metadata_path).resolve() if metadata_path is not None else None
        if source == output:
            raise ValueError("input and output must be different paths; source files are never overwritten")
        if metadata is not None and metadata in {source, output}:
            raise ValueError("metadata must be a different path from input and output")
        if output.suffix.lower() != ".png":
            raise ValueError("output must be a PNG path ending in .png")
        if not source.is_file():
            raise FileNotFoundError(f"input image does not exist: {source}")
        try:
            # Let the core apply EXIF orientation and mode conversion once
            # while the lazy PIL decoder is still inside its file context.
            with Image.open(source) as opened:
                result, info = self.normalize(opened)
            output.parent.mkdir(parents=True, exist_ok=True)
            result.save(output, format="PNG")
            if metadata is not None:
                _write_json(metadata, _metadata_payload(source, output, info, config=self.config))
            return FileResult(source=source, output=output, metadata=metadata, info=info)
        except Exception as exc:
            error = f"{type(exc).__name__}: {exc}"
            if metadata is not None:
                _write_json(metadata, _metadata_payload(source, output, None, config=self.config, error=error))
            raise

    def process_many(
        self,
        inputs: Sequence[PathLike],
        *,
        output_dir: PathLike = DEFAULT_OUTPUT_DIR,
        recursive: bool = True,
        save_metadata: bool = True,
        manifest_path: Optional[PathLike] = None,
        progress: Optional[ProgressCallback] = None,
        continue_on_error: bool = True,
    ) -> list[FileResult]:
        """Process files/folders in one model session.

        By default each successful item gets a same-stem JSON beside its PNG.
        Set ``manifest_path`` to additionally write one aggregate JSON report.
        Individual failures are returned in the result list when
        ``continue_on_error`` is true.
        """

        destination = _safe_resolve(_as_path(output_dir))
        # The destination can sit below a folder supplied as input.  Exclude
        # that subtree during directory expansion so a second run never feeds
        # generated PNGs back into the model.  A deliberately supplied image
        # file remains valid and receives a safe output suffix.
        sources = collect_image_paths(
            inputs,
            recursive=recursive,
            excluded_directories=(destination,),
        )
        if not sources:
            raise ValueError("没有找到可处理的图片（支持 JPG、PNG、WEBP、TIFF、BMP）。")
        allocated = _allocate_output_paths(sources, destination)

        manifest: Optional[Path] = None
        if manifest_path is not None:
            manifest = _safe_resolve(_as_path(manifest_path))
            source_keys = {_path_key(source) for source in sources}
            if _path_key(manifest) in source_keys:
                raise ValueError("manifest path must not overwrite an input image")
            # A directory input may contain the destination subtree, which is
            # intentionally excluded above.  Still reject a manifest that is
            # plainly one of the caller's input paths (or an image path below
            # a supplied input directory), even when that file was filtered
            # from the processing list.
            for raw in inputs:
                raw_path = _safe_resolve(_as_path(raw))
                if raw_path.is_file() and _path_key(raw_path) == _path_key(manifest):
                    raise ValueError("manifest path must not overwrite an input image")
                if raw_path.is_dir() and _is_within(manifest, raw_path):
                    if manifest.suffix.lower() in IMAGE_EXTENSIONS:
                        raise ValueError("manifest path must not overwrite an input image")
            artifact_keys = {
                _path_key(path)
                for output, metadata in allocated
                for path in (output, metadata)
            }
            if _path_key(manifest) in artifact_keys:
                raise ValueError("manifest path must be different from per-image outputs")
            if manifest.exists() and manifest.is_dir():
                raise ValueError("manifest path must be a file, not a directory")

        destination.mkdir(parents=True, exist_ok=True)
        results: list[FileResult] = []
        total = len(sources)
        for index, (source, (output, metadata)) in enumerate(zip(sources, allocated), start=1):
            if progress is not None:
                progress(index, total, source)
            metadata_target = metadata if save_metadata else None
            try:
                result = self.process_file(source, output, metadata_path=metadata_target)
                results.append(result)
            except Exception as exc:
                error_text = f"{type(exc).__name__}: {exc}"
                _clear_exception_traceback(exc)
                _release_torch_memory(str(getattr(self._backend, "device", self.config.device)))
                failed = FileResult(
                    source=source,
                    output=None,
                    metadata=metadata_target,
                    info=None,
                    error=error_text,
                )
                results.append(failed)
                if not continue_on_error:
                    # The propagated traceback can otherwise retain this
                    # method's frame (and transient image references) in a
                    # long-lived caller.  Keep the exception type/message but
                    # detach those frames before re-raising.
                    _clear_exception_traceback(exc)
                    # Fail-fast callers are abandoning this batch.  Release
                    # the owned model now instead of leaving a large
                    # accelerator allocation attached to the reusable wrapper.
                    self.close()
                    raise
        if manifest is not None:
            manifest_payload = {
                "success": all(item.succeeded for item in results),
                "backend": self.config.backend,
                "model": self.config.effective_model,
                "device": self.config.device,
                "items": [
                    {
                        "source": str(item.source),
                        "output": (str(item.output) if item.output is not None else None),
                        "metadata": (str(item.metadata) if item.metadata is not None else None),
                        "succeeded": item.succeeded,
                        "error": item.error,
                        "info": (asdict(item.info) if item.info is not None else None),
                    }
                    for item in results
                ],
            }
            _write_json(manifest, manifest_payload)
        return results


def process_many(
    inputs: Sequence[PathLike],
    *,
    config: Optional[NormalizerConfig] = None,
    output_dir: PathLike = DEFAULT_OUTPUT_DIR,
    recursive: bool = True,
    save_metadata: bool = True,
    manifest_path: Optional[PathLike] = None,
    progress: Optional[ProgressCallback] = None,
    continue_on_error: bool = True,
    backend_instance: Optional[Any] = None,
) -> list[FileResult]:
    """Functional convenience wrapper around :class:`Normalizer`."""

    normalizer = Normalizer(config, backend_instance=backend_instance)
    try:
        return normalizer.process_many(
            inputs,
            output_dir=output_dir,
            recursive=recursive,
            save_metadata=save_metadata,
            manifest_path=manifest_path,
            progress=progress,
            continue_on_error=continue_on_error,
        )
    finally:
        # The functional helper has no object for the caller to close later;
        # release its owned model deterministically on both success and error.
        normalizer.close()


__all__ = [
    "DEFAULT_MAX_GEOMETRY_PIXELS",
    "DEFAULT_BIREFNET_MAX_SIDE",
    "DEFAULT_BIREFNET_CPU_FALLBACK_MAX_SIDE",
    "DEFAULT_BACKEND",
    "DEFAULT_MODEL",
    "DEFAULT_OUTPUT_DIR",
    "IMAGE_EXTENSIONS",
    "BatchResult",
    "FileResult",
    "Normalizer",
    "NormalizerConfig",
    "ProcessingInfo",
    "collect_image_paths",
    "create_segmentation_backend",
    "process_many",
    "parse_max_geometry_pixels",
    "validate_geometry_size",
]
